package main

import (
	"fmt"
	"io"
	"os"
	"strings"
)

func main() {
	if len(os.Args) != 2 {
		fmt.Println("Usage: generate_ast <output directory>")
		os.Exit(64)
	}
	outputDir := os.Args[1]
	fmt.Printf("output directory: %s\n", outputDir)

	defineAst(outputDir, "Expr", []string{
		"Binary	  : left Expr, operator Token, right Expr",
		"Grouping : expression Expr",
		"Literal  : value any",
		"Unary    : operator TokenType, right Expr",
	})
}

func defineAst(outputDir string, baseName string, types []string) {
	path := fmt.Sprintf("%s/%s.go", outputDir, strings.ToLower(baseName))

	file, err := os.OpenFile(path, os.O_WRONLY|os.O_CREATE, 0666)
	if err != nil {
		panic(fmt.Sprintf("Failed to open output file: %s\n", path))
	}
	defer file.Close()

	fmt.Fprintln(file, "// generated by generate_ast tool. Do not edit.")
	fmt.Fprintln(file, "package lox")
	fmt.Fprintln(file)
	defineVisitor(file, baseName, types)
	fmt.Fprintln(file)
	fmt.Fprintln(file, "type "+baseName+" interface {")
	fmt.Fprintf(file, "  Accept(visitor %sVisitor) any\n", baseName)
	fmt.Fprintln(file, "}")
	fmt.Fprintln(file)

	for _, tokenTokenType := range types {
		className := strings.Split(tokenTokenType, ":")[0]
		fields := strings.Split(tokenTokenType, ":")[1]
		className = strings.TrimSpace(className)
		fields = strings.TrimSpace(fields)
		defineTokenType(file, baseName, className, fields)
	}
}

func defineTokenType(file io.Writer, baseName string, className string, fieldList string) {
	fmt.Fprintln(file, "// ", "-------------------------------------------------------------")
	fields := strings.Split(fieldList, ",")
	fmt.Fprintln(file, "type "+className+" struct {")

	for _, field := range fields {
		field = strings.TrimSpace(field)
		fmt.Fprintln(file, "  "+field)
	}
	fmt.Fprintln(file, "}")
	fmt.Fprintln(file)

	fmt.Fprintf(file, "func New%s(%s) %s {\n", className, fieldList, className)
	fmt.Fprintf(file, "  return %s{\n", className)
	for _, field := range fields {
		field = strings.TrimSpace(field)
		name := strings.Split(field, " ")[0]
		fmt.Fprintf(file, "    %s:%s,\n", name, name)
	}
	fmt.Fprintln(file, "  }")
	fmt.Fprintln(file, "}")
	fmt.Fprintln(file)

	fmt.Fprintf(file, "func (c %s) Accept(visitor %sVisitor) any {\n", className, baseName)
	fmt.Fprintf(file, "  return visitor.Visit%s(c)\n", className)
	fmt.Fprintf(file, "}\n")

}

func defineVisitor(file io.Writer, baseName string, types []string) {
	fmt.Fprintf(file, "type %sVisitor interface {\n", baseName)
	for _, aType := range types {
		typeName := strings.TrimSpace(strings.Split(aType, ":")[0])
		base := strings.ToLower(baseName)
		fmt.Fprintf(file, "  Visit%s(%s %s) any\n", typeName, base, typeName)
	}
	fmt.Fprintln(file, "}")

}
