// generated by generate_ast tool. Do not edit.
package lox

type ExprVisitor interface {
  VisitAssignmentExpr(expr AssignmentExpr) (any, LoxError)
  VisitBinaryExpr(expr BinaryExpr) (any, LoxError)
  VisitGroupingExpr(expr GroupingExpr) (any, LoxError)
  VisitLiteralExpr(expr LiteralExpr) (any, LoxError)
  VisitUnaryExpr(expr UnaryExpr) (any, LoxError)
  VisitVariableExpr(expr VariableExpr) (any, LoxError)
}

type Expr interface {
  Accept(visitor ExprVisitor) (any, LoxError)
}

//  -------------------------------------------------------------
type AssignmentExpr struct {
  name Token
  value Expr
}

func NewAssignmentExpr(name Token, value Expr) AssignmentExpr {
  return AssignmentExpr{
    name:name,
    value:value,
  }
}

func (c AssignmentExpr) Accept(visitor ExprVisitor) (any, LoxError) {
  return visitor.VisitAssignmentExpr(c)
}
//  -------------------------------------------------------------
type BinaryExpr struct {
  left Expr
  operator Token
  right Expr
}

func NewBinaryExpr(left Expr, operator Token, right Expr) BinaryExpr {
  return BinaryExpr{
    left:left,
    operator:operator,
    right:right,
  }
}

func (c BinaryExpr) Accept(visitor ExprVisitor) (any, LoxError) {
  return visitor.VisitBinaryExpr(c)
}
//  -------------------------------------------------------------
type GroupingExpr struct {
  expression Expr
}

func NewGroupingExpr(expression Expr) GroupingExpr {
  return GroupingExpr{
    expression:expression,
  }
}

func (c GroupingExpr) Accept(visitor ExprVisitor) (any, LoxError) {
  return visitor.VisitGroupingExpr(c)
}
//  -------------------------------------------------------------
type LiteralExpr struct {
  value any
}

func NewLiteralExpr(value any) LiteralExpr {
  return LiteralExpr{
    value:value,
  }
}

func (c LiteralExpr) Accept(visitor ExprVisitor) (any, LoxError) {
  return visitor.VisitLiteralExpr(c)
}
//  -------------------------------------------------------------
type UnaryExpr struct {
  operator Token
  right Expr
}

func NewUnaryExpr(operator Token, right Expr) UnaryExpr {
  return UnaryExpr{
    operator:operator,
    right:right,
  }
}

func (c UnaryExpr) Accept(visitor ExprVisitor) (any, LoxError) {
  return visitor.VisitUnaryExpr(c)
}
//  -------------------------------------------------------------
type VariableExpr struct {
  name Token
}

func NewVariableExpr(name Token) VariableExpr {
  return VariableExpr{
    name:name,
  }
}

func (c VariableExpr) Accept(visitor ExprVisitor) (any, LoxError) {
  return visitor.VisitVariableExpr(c)
}
