// generated by generate_ast tool. Do not edit.
package lox

type StmtVisitor interface {
  VisitExpressionStmt(stmt ExpressionStmt) (any, LoxError)
  VisitPrintStmt(stmt PrintStmt) (any, LoxError)
}

type Stmt interface {
  Accept(visitor StmtVisitor) (any, LoxError)
}

//  -------------------------------------------------------------
type ExpressionStmt struct {
  expression Expr
}

func NewExpressionStmt(expression Expr) ExpressionStmt {
  return ExpressionStmt{
    expression:expression,
  }
}

func (c ExpressionStmt) Accept(visitor StmtVisitor) (any, LoxError) {
  return visitor.VisitExpressionStmt(c)
}
//  -------------------------------------------------------------
type PrintStmt struct {
  expression Expr
}

func NewPrintStmt(expression Expr) PrintStmt {
  return PrintStmt{
    expression:expression,
  }
}

func (c PrintStmt) Accept(visitor StmtVisitor) (any, LoxError) {
  return visitor.VisitPrintStmt(c)
}
