// generated by generate_ast tool. Do not edit.
package lox

type StmtVisitor interface {
  VisitExpressionStmt(stmt ExpressionStmt) (any, LoxError)
  VisitIfStmt(stmt IfStmt) (any, LoxError)
  VisitPrintStmt(stmt PrintStmt) (any, LoxError)
  VisitBlockStmt(stmt BlockStmt) (any, LoxError)
  VisitVarStmt(stmt VarStmt) (any, LoxError)
}

type Stmt interface {
  Accept(visitor StmtVisitor) (any, LoxError)
}

//  -------------------------------------------------------------
type ExpressionStmt struct {
  expression Expr
}

func NewExpressionStmt(expression Expr) ExpressionStmt {
  return ExpressionStmt{
    expression:expression,
  }
}

func (c ExpressionStmt) Accept(visitor StmtVisitor) (any, LoxError) {
  return visitor.VisitExpressionStmt(c)
}
//  -------------------------------------------------------------
type IfStmt struct {
  condition Expr
  thenBranch Stmt
  elseBranch Stmt
}

func NewIfStmt(condition Expr, thenBranch Stmt, elseBranch Stmt) IfStmt {
  return IfStmt{
    condition:condition,
    thenBranch:thenBranch,
    elseBranch:elseBranch,
  }
}

func (c IfStmt) Accept(visitor StmtVisitor) (any, LoxError) {
  return visitor.VisitIfStmt(c)
}
//  -------------------------------------------------------------
type PrintStmt struct {
  expression Expr
}

func NewPrintStmt(expression Expr) PrintStmt {
  return PrintStmt{
    expression:expression,
  }
}

func (c PrintStmt) Accept(visitor StmtVisitor) (any, LoxError) {
  return visitor.VisitPrintStmt(c)
}
//  -------------------------------------------------------------
type BlockStmt struct {
  statements []Stmt
}

func NewBlockStmt(statements []Stmt) BlockStmt {
  return BlockStmt{
    statements:statements,
  }
}

func (c BlockStmt) Accept(visitor StmtVisitor) (any, LoxError) {
  return visitor.VisitBlockStmt(c)
}
//  -------------------------------------------------------------
type VarStmt struct {
  name Token
  initializer Expr
}

func NewVarStmt(name Token, initializer Expr) VarStmt {
  return VarStmt{
    name:name,
    initializer:initializer,
  }
}

func (c VarStmt) Accept(visitor StmtVisitor) (any, LoxError) {
  return visitor.VisitVarStmt(c)
}
